version: "3.3"
services:
  dbase:
    build:
      context: .
      dockerfile: Dockerfile-database
    container_name: dbase
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}